/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as SpectralRouteImport } from './routes/spectral'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectralRoute = SpectralRouteImport.update({
  id: '/spectral',
  path: '/spectral',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/evidence': typeof EvidenceRoute
  '/receipts': typeof ReceiptsRoute
  '/spectral': typeof SpectralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/evidence': typeof EvidenceRoute
  '/receipts': typeof ReceiptsRoute
  '/spectral': typeof SpectralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/evidence': typeof EvidenceRoute
  '/receipts': typeof ReceiptsRoute
  '/spectral': typeof SpectralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/batch' | '/evidence' | '/receipts' | '/spectral'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/batch' | '/evidence' | '/receipts' | '/spectral'
  id: '__root__' | '/' | '/batch' | '/evidence' | '/receipts' | '/spectral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchRoute: typeof BatchRoute
  EvidenceRoute: typeof EvidenceRoute
  ReceiptsRoute: typeof ReceiptsRoute
  SpectralRoute: typeof SpectralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectral': {
      id: '/spectral'
      path: '/spectral'
      fullPath: '/spectral'
      preLoaderRoute: typeof SpectralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchRoute: BatchRoute,
  EvidenceRoute: EvidenceRoute,
  ReceiptsRoute: ReceiptsRoute,
  SpectralRoute: SpectralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
